---
os: linux
sudo: required

language: php
php: 7.2

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - env: TESSERACT_VERSION=3.03
    - env: TESSERACT_VERSION=3.04
    - env: TESSERACT_VERSION=3.05

services:
  - docker

before_script:
  - composer install

script:
  - php tests/test-runner.php unit $(test -v TESSERACT_VERSION && echo functional)

after_success:
  - test -v TESSERACT_VERSION && vendor/bin/codacycoverage clover ./coverage.xml

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/acba3130175a3a47266d'
    on_success: always
    on_failure: always
    on_start: always
