#!/usr/bin/env sh
BASEDIR=$(cd "$(dirname "$0")/.."; pwd)
IMAGESDIR=$(cd "$BASEDIR/images"; pwd)

docker run -it --rm \
	-v $IMAGESDIR:$IMAGESDIR \
	-w $BASEDIR \
	thiagoalessio/tesseract:$TESSERACT_VERSION $@ | tr -d '\r'
